name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.0.1'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.0.1'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
